# Generated by Django 5.1.3 on 2024-12-11 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_comment_to_recipe_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='to_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='recipes.recipe'),
        ),
    ]
